### ISSUE TITLE
Changes to Robot

### ISSUE THREAD

**Issue by pcehn1421** [IanWold/CS2820#4]
Hi all, I've just changed robot to accept 4 different kind of orders. 1. picks up shelf from loading dock and drops at shelf area(default) or given coordinates. 2. picks up from shelf area or given coordinates and drops at loading dock. 3. picks up from shelf area or given coordinate and drops at shelf drop. 4. picks up at shelf drop  and drops at shelf area or given coordinate.

**Comment by spikesdphan** [comment]
Hey I was wondering if you had a method to pick up a certain shelf that an item is on? Also, when you call the "giveCommand" method, you have to give it an x and a y, why is that?

**Comment by pcehn1421** [comment]
I don't think the robot can actually see the shelf or whats on it. It can only see the shelf id given to it. As for the "giveCommand" method the x and y is suppose to tell the robot where to put the shelf around the shelving area. Since we only have one shelf just give it the default ( 6,3).

**Comment by pcehn1421** [comment]
I've just changed the giveCommand() function so that giving x and y 0,0 will trigger them to have the default value 6,3.
