### ISSUE TITLE
Another note for floor 

### ISSUE THREAD

**Issue by pcehn1421** [IanWold/CS2820#5]
I've just changed the robot to use a queue of tiles. Lemme now if that works for you.

**Comment by pcehn1421** [comment]
One more thing, for some reason I'm still getting a null pointer exception at line 218.

here's transcript:
Current   x:4 y:6
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 7
	at Warehouse.Floor.getPath(Floor.java:218)
	at Warehouse.Robot2.genPath(Robot2.java:174)
	at Warehouse.Robot2.tick(Robot2.java:127)
	at Warehouse.Robot2.main(Robot2.java:315)
Goal    x6 y:3

Can you look into it? Thanks.

**Comment by pcehn1421** [comment]
Hey Patrick, I figured out the out of bounds error. The program was trying to look at a tile not in the floor area. e.g it was trying to figure out if [x][y+1] is a "road" type when y was already 6 thus triggering the out of bounds error. But after I fixed it the program seems to go in to a infinite loop of the following:

Current   x:4 y:5
Goal    x6 y:3
distup:3.999999960555127E7 distdown:2.23606797749979 distleft:3.605551275463989 distright2.23606797749979

I've changed your code in the clone I created (FloorRobotTest) but not in the original. Can you see what's going on? Thanks.

**Comment by pverbrugge** [comment]
Is that not fixed? I thought I fixed that error last night? The test file compiled and gave me true are you testing anther two points?
⁣

**Comment by pcehn1421** [comment]
I was testing points 4,6 to 6,3

**Comment by pverbrugge** [comment]
Alright I thought I fixed those out of bounds but I'll check them when I get home⁣

**Comment by pcehn1421** [comment]
Ok Thanks!

**Comment by pverbrugge** [comment]
Fixed it, I forgot arrays start at zero so I had to decrease the check by 1 and it worked.⁣

**Comment by pcehn1421** [comment]
Okay I'll go test it

**Comment by pcehn1421** [comment]
Somehow right now i gets stuck on a infinite loop when going from 6,3 to 8,6

**Comment by pcehn1421** [comment]
I've made a recursive version of your getPath() function. It works pretty well. We can use that Function if you don't mind. You can check it out in FloorRobotTest2.java. It's called runPath().
