### ISSUE TITLE
Changes for Robot from Viz (Notes for master too)

### ISSUE THREAD

**Issue by ka11inator** [IanWold/CS2820#8]
Hi Robot,
So the term "Robot" is actually a built in type for java, so please start using "Robot1.java" so that other parts of the project can find it.
I had a lot of issues with your scheduling and how that would be implemented. I could not get it to compile. 
Viz.java takes in a Robot1 in its constructor when creating the grid and uses its X and Y values to show the location. Those parts worked fine but I had issues with other parts.
Hopefully when fully implemented it will be fine..
From,
Visualizer (Kallin Khan)

**Comment by ka11inator** [comment]
Also if you could add a method that says when the robot is carrying a shelf, that would make it asks for me to show the shelf moving as well

**Comment by pcehn1421** [comment]
I'll have all the compiling issues sorted out as soon as possible after I figure everything out with floor. As for a method to see if the robot has a shelf : it's already in the there - it's called hasObject and whenever its called it will return a Boolean telling you if the robot is carrying. please let me know if you have anyone questions.

**Comment by pcehn1421** [comment]
Robot is finalized
