### ISSUE TITLE
Note for Master

### ISSUE THREAD

**Issue by pcehn1421** [IanWold/CS2820#9]
Since robot uses a copy of the master floor as a constructor so I don't think the master floor changes when the robot ticks. Thus, I've added a getFloor() method to robot so that you can sync the floors on each tick. I can also add setFloor() if needed to. Let me know if you have any questions.

**Comment by IanWold** [comment]
Should I call getFloor() after each tick, then?

**Comment by pcehn1421** [comment]
yup, I think that covers it
